### ISSUE TITLE
Remember Me control name changed

### ISSUE THREAD

**Issue by FlyingDiver** [jantman/xfinity-usage#14]
Line 150:
`                rem_me = self.browser.find_element_by_id('remember_me')`
needs to be changed to:
`                rem_me = self.browser.find_element_by_id('remember_me_checkbox')`

This is for Comcast in Southwest Florida.  Not sure if it's a regional difference or not.

**Comment by jantman** [comment]
@FlyingDiver thanks for this. I commented on your PR #15, I actually had more-or-less the same fix in a branch waiting for the user who reported #13 to verify the fix, but haven't heard back.

**Comment by jantman** [comment]
@FlyingDiver I've merged my #13 which makes a very similar fix, and released it as 2.0.2. That seems to fix the problem for me. If you have further issues, please feel free to reopen this.

Thank you so much for taking the time to open this issue. Apologies for the confusion around it.
