### ISSUE TITLE
Feature Request: InfluxDB

### ISSUE THREAD

**Issue by aberrix** [jantman/xfinity-usage#17]
## Feature Request
InfluxDB compatibility 

### Feature Description
Would love to get this to work with InfluxDB

**Comment by billimek** [comment]
In the meantime, you can take a look at this implementation using this xfinity-usage library for influxdb support: https://github.com/billimek/comcastUsage-for-influxdb

**Comment by aberrix** [comment]
great scott! this is exactly what I was looking for and further simplifies things. Thanks!
