### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by NickBusey** [jantman/xfinity-usage#20]
I've been using this project inside my other project HomelabOS, and have been working on a nice Docker wrapper for it. I'd be happy to take over on this for you. Thanks for your great work on it!

**Comment by jantman** [comment]
@NickBusey I'm really sorry it took me so long to get around to replying to this, things have been really busy lately. Are you still interested?

**Comment by NickBusey** [comment]
No worries! Sorry in the mean time I found https://kibitzr.github.io/ and think I'm going to use that.
