### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by billimek** [jantman/xfinity-usage#21]
### Feature Description

It would be great if we could build this code into a Docker image.  The current approach leaves a docker implementation up to the users.  I actually [created a repo](https://github.com/billimek/comcastUsage-for-influxdb) whereby new versions of this get [packaged into a docker image](https://hub.docker.com/r/billimek/comcastusage-for-influxdb/) but wonder if it would be better for the image creation to be consolidated here for the following use-cases:

### Use Cases

* Docker: Some folks want to run this as a docker container in order to isolate workloads
* Kubernetes: I actually wrote a [helm chart](https://github.com/billimek/billimek-charts/tree/master/comcast) to run this as a kubernetes pod, and it works great

### Testing Assistance

I can totally test this!

I'm willing to take a crack at a PR to add-in the Docker image creation, if this is a wanted feature.

**Comment by jantman** [comment]
@billimek I actually switched from Xfinity to AT&T last month and am actively looking for a maintainer for this project as I no longer have a way of testing it. If you're interested in taking over, let me know... I actually got one person who seemed interested ( #20 ) but I missed the issue for a while and it's now closed.

A PR to handle the Docker build would definitely be welcome, but I'd really prefer to let a/the new maintainer handle merging it.

**Comment by billimek** [comment]
Hi @jantman sure I actually thought that @NickBusey already took over!  If he's gone MIA I'm happy to.

Also, I'm super envious of your AT&T (assuming it's fiber service and no horrible ~data caps~ managed service plans) - good for you!

**Comment by NickBusey** [comment]
I think I'm going to use https://kibitzr.github.io/ as a more general purpose solution. Have at it @billimek . Thanks!

**Comment by jantman** [comment]
Sorry for the delay, @billimek. Ok, cool!

How would you like to handle the transition? On PyPI I can add whatever email you use there as an owner of the package. For this repo, I've added you as a collaborator. Does that work for you?

Heh, thanks! Yeah it's fiber... I just moved in here in June and they lit the block with fiber two months later, so I was incredibly happy about that (aside from the Xfinity termination fee for canceling after 3 months). I currently have the 300Mbps (**symmetrical**) plan for $70/month which has a 1TB data cap. I rarely use that much... if it becomes an issue, for $90 or $95 I can get Gigabit symmetrical with no cap.

**Comment by billimek** [comment]
> How would you like to handle the transition? On PyPI I can add whatever email you use there as an owner of the package. For this repo, I've added you as a collaborator. Does that work for you?

Yes, certainly!  Can you add: jeff@billimek.com ?

**Comment by jantman** [comment]
@billimek Ok, it looks like I need your PyPI _username_, not email, to add you as a maintainer...

**Comment by jantman** [comment]
Ok, I've added you as a maintainer on PyPI.

I'm really not sure regarding the Travis builds. I _think_ that for the time being, with contributor/commit access to this repo you should be able to do whatever you need with Travis. Let me know if that's not the case and we'll figure something out.

**Comment by billimek** [comment]
The docker image linked does something different (uses this python lib and emits the data to influxdb) and may not be appropriate for this repo.  Instead it may make more sense to reference the Dockerfile in the readme here instead of combining the functionality into a single repo.
