### ISSUE TITLE
The script fails if current directory is not writable.

### ISSUE THREAD

**Issue by Artem-B** [jantman/xfinity-usage#3]
Apparently the script attempts to write a log to ghostdriver.log and crashes when that fails.
E.g. attempting to run it under user nobody with / as its effective home directory didn't work:

Traceback (most recent call last):
  File "/usr/home/XXX/work/xfinity-usage/xfinity_usage.py", line 530, in <module>
    res = script.run()
  File "/usr/home/XXX/work/xfinity-usage/xfinity_usage.py", line 152, in run
    self.browser.quit()
AttributeError: 'XfinityUsage' object has no attribute 'browser'

**Comment by Artem-B** [comment]
Looks like there is a way to change log location or disable it:
https://blog.michaelyin.info/2015/05/18/how-to-disable-ghostdriver-log-when-using-selenium/

**Comment by jantman** [comment]
@Artem-B as far as I know, that's common to anything using Selenium (or at least the Python selenium bindings). If you're running as a user that can't write to its home directory, how about changing the current directory to ``/tmp`` or somewhere else the user can write?

If you feel strongly about changing the log location or disabling it, PRs are welcome.

**Comment by jantman** [comment]
Closing unless I hear back or get a PR.
