### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by OverloadUT** [jantman/xfinity-usage#4]
Hey there!

I would like to use this library to implement a Comcast data usage component in https://github.com/home-assistant/home-assistant

However, you do not seem to have any license attached to this repo. Would you mind adding one so we can use your code? :)

Thanks!

Edit: Ah ha, I just noticed that there is a license commented right in to the code

**Comment by jantman** [comment]
Yeah... I know that's not a "real license", so I'm not sure if that's considered good enough for legal purposes. If the script is included as-is, it certainly wouldn't be a problem... to be honest, holy wars aside, all of my non-trivial work is licensed AGPLv3... 

On the other hand... honestly phantomjs and selenium is a bit heavy-weight for a widget. I'm sort of wondering if someone really clever could implement this in something with fewer dependencies...

**Comment by jantman** [comment]
Is the license in the comment header sufficient for your purposes?

**Comment by OverloadUT** [comment]
Yeah I believe it would be just fine. I'll come back if not!

Good point about the overhead of phantomjs and Selenium - I'll talk to the Home Assistant maintainers to get their thoughts on that one

**Comment by jantman** [comment]
Ok, sounds good, I'll close this for now.

So I'm not sure offhand how much of this site is done client-side with javascript, or whether there's a modern alternative to phantomjs/selenium that could do this. But I'd assume that HomeAssistant has other components with external dependencies, so maybe it's not that bad. I'd just make sure you wrap this in something that will fail gracefully if phantomjs and/or selenium aren't available.
