### ISSUE TITLE
publish to pypi?

### ISSUE THREAD

**Issue by billimek** [jantman/xfinity-usage#9]
Is it possible to publish this project to the [pypi](https://pypi.python.org/) python repository?  

It should be possible to do via a simple travis job and would allow others to make use of the changes without needing to clone this repo and copy the file.

If there is interest, I can help with a PR to get the travis part started.

**Comment by jantman** [comment]
I can try to get around to that this weekend. I'd prefer to keep it local, as I don't have my PyPI creds in Travis and would prefer to keep it that way.

**Comment by jantman** [comment]
@billimek Fixed. I just cut 2.0.0 and uploaded to PyPI. This release also introduces support for optionally sending metrics to Graphite. The entrypoint is documented in README, ``xfinity-usage``.
